import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-container": "#a7c1f7",
        "inverse-on-surface": "#9b9d9e",
        "surface-container-highest": "#dadddf",
        "on-error": "#ffefee",
        "surface-container-high": "#e0e3e4",
        "surface-variant": "#dadddf",
        "on-tertiary-fixed": "#042754",
        "on-secondary": "#fff2ce",
        "on-primary": "#f1f2ff",
        "on-surface-variant": "#595c5d",
        background: "#f5f6f7",
        surface: "#f5f6f7",
        "surface-dim": "#d1d5d7",
        "on-tertiary": "#eff2ff",
        "on-surface": "#2c2f30",
        "tertiary-fixed-dim": "#9ab4e9",
        "on-secondary-fixed": "#433700",
        "primary-fixed-dim": "#618eff",
        "surface-tint": "#0253cd",
        "secondary-dim": "#5f4e00",
        "on-primary-fixed": "#000000",
        "on-secondary-fixed-variant": "#645300",
        "error-dim": "#9f0519",
        "secondary-container": "#fdd400",
        "tertiary-fixed": "#a7c1f7",
        "inverse-primary": "#5c8bff",
        "primary-dim": "#0048b5",
        "inverse-surface": "#0c0f10",
        primary: "#0253cd",
        "surface-container": "#e6e8ea",
        "primary-container": "#789dff",
        "on-tertiary-container": "#203c6a",
        "on-primary-container": "#001f57",
        "tertiary-dim": "#354f7e",
        tertiary: "#415b8b",
        secondary: "#6d5a00",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed-variant": "#2a4573",
        "primary-fixed": "#789dff",
        "surface-bright": "#f5f6f7",
        "on-error-container": "#570008",
        "secondary-fixed": "#fdd400",
        "on-primary-fixed-variant": "#00276b",
        "on-secondary-container": "#594a00",
        "secondary-fixed-dim": "#edc600",
        outline: "#757778",
        "outline-variant": "#abadae",
        "surface-container-low": "#eff1f2",
        "error-container": "#fb5151",
        error: "#b31b25",
        "on-background": "#2c2f30",
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        lg: "0.75rem",
        xl: "1rem",
        '2xl': "1.25rem",
        '3xl': "1.5rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["var(--font-sora)", "sans-serif"],
        body: ["var(--font-manrope)", "sans-serif"],
        label: ["var(--font-manrope)", "sans-serif"],
      },
      spacing: {
        0: "0px",
        1: "2px",
        2: "4px",
        3: "6px",
        4: "8px",
        6: "12px",
        8: "16px",
        12: "24px",
        16: "32px",
        24: "48px",
        32: "64px",
        48: "96px",
        64: "128px",
      },
      keyframes: {
        fadeInUp: {
          "0%": { opacity: "0", transform: "translateY(40px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        slideUp: {
          "0%": { opacity: "0", transform: "translateY(60px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        scaleIn: {
          "0%": { opacity: "0", transform: "scale(0.95)" },
          "100%": { opacity: "1", transform: "scale(1)" },
        },
        "pulse-subtle": {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.8" },
        },
        shake: {
          "0%, 100%": { transform: "translateX(0)" },
          "25%": { transform: "translateX(-2px)" },
          "75%": { transform: "translateX(2px)" },
        },
        slideInRight: {
          "0%": { opacity: "0", transform: "translateX(100px)" },
          "100%": { opacity: "1", transform: "translateX(0)" },
        },
      },
      animation: {
        "fade-in-up": "fadeInUp 0.6s cubic-bezier(0.4, 0, 0.2, 1)",
        "slide-up": "slideUp 0.6s cubic-bezier(0.4, 0, 0.2, 1)",
        "scale-in": "scaleIn 0.5s cubic-bezier(0.4, 0, 0.2, 1)",
        "pulse-subtle": "pulse-subtle 2s cubic-bezier(0.4, 0, 0.6, 1)",
        "shake-error": "shake 0.3s cubic-bezier(0.36, 0, 0.66, 1)",
        "slide-in-right": "slideInRight 0.3s cubic-bezier(0.4, 0, 0.2, 1)",
      },
      boxShadow: {
        "elevation-1": "0 2px 4px rgba(0, 0, 0, 0.08)",
        "elevation-2": "0 4px 8px rgba(0, 0, 0, 0.12)",
        "elevation-3": "0 8px 16px rgba(0, 0, 0, 0.14)",
        "elevation-4": "0 16px 24px rgba(0, 0, 0, 0.16)",
        "glass": "0 8px 32px rgba(31, 38, 135, 0.1)",
      },
    },
  },
  plugins: [],
};
export default config;
